### ISSUE TITLE
Signing performance

### ISSUE THREAD

**Issue by jasny** [ltonetwork/seasalt#19]
Make sure that the underlying (bouncy castle) objects are created in the constructor and not each time a (`sign`, `verify`, etc) function is called.

**Comment by jasny** [comment]
https://github.com/ltonetwork/seasalt/blob/main/src/main/java/com/ltonetwork/seasalt/sign/Ed25519.java#L37

**Comment by KaloyanTanev** [comment]
Observation:
seasalt is ~x1.5 faster in verifying
nacl is ~x3.5 faster in signing
